### ISSUE TITLE
Not all messages are in Loki

### ISSUE THREAD

**Issue by NicolaeCh** [ThePrez/Manzan#231]
Is there any predefined message list to supervise?  I only receive: _"CPIAD09 (severity 0): El usuario SAYTEL del cliente 127.0.0.1 se ha conectado al trabajo 165710/QUSER/QZRCSRVS del subsistema QUSRWRK de QSYS el 25/06/25 08:49:57."_  There are others in history log. 

This is my configuration - I set the interval to 60 sec  as this is a test system with very little activity: 

dests.ini
[loki_out]
type=loki
url=http://10.244.164.146:3100
username=abc1234
password=trtyuobv

[watcher1]
type=watch
id=QSYSOPR
destinations=loki_out
format=$MESSAGE_ID$ (severity $SEVERITY$): $MESSAGE$
strwch=WCHMSG((*ALL)) WCHMSGQ((QSYS/QSYSOPR))
interval=60000
numToProcess=100
enabled=true

[watchout]
type=watch
id=ansible1
destinations=loki_out
format=$MESSAGE_ID$ (severity $SEVERITY$): $MESSAGE$
strwch=WCHMSG((*ALL)) WCHMSGQ((*HSTLOG))
interval=60000
numToProcess=100
enabled=true

**My history log look like that (I expected to see all the messages in loki):**
_Job 165796/QUSER/QSCWCHPS ended on 25/06/25 at 09:00:00; 0,055 seconds used;  
Job 165792/QUSER/QSCWCHPS ended on 25/06/25 at 09:00:00; 0,029 seconds used;  
*SIGNON server job 165376/QUSER/QZSOSIGN processing request for user SAYTEL o 
User SAYTEL from client 127.0.0.1 connected to job 165436/QUSER/QZDASOINIT in 
Job 165804/QUSER/QSCWCHPS started on 25/06/25 at 09:00:59 in subsystem QUSRWR 
Job 165805/QUSER/QSCWCHPS started on 25/06/25 at 09:00:59 in subsystem QUSRWR 
Job 165800/QUSER/QSCWCHPS ended on 25/06/25 at 09:00:59; 0,051 seconds used;  
Job 165798/QUSER/QSCWCHPS ended on 25/06/25 at 09:00:59; 0,030 seconds used;  
*SIGNON server job 165376/QUSER/QZSOSIGN processing request for user SAYTEL o 
User SAYTEL from client 127.0.0.1 connected to job 165436/QUSER/QZDASOINIT in 
Job 165806/QUSER/QSCWCHPS started on 25/06/25 at 09:01:00 in subsystem QUSRWR 
Job 165807/QUSER/QSCWCHPS started on 25/06/25 at 09:01:00 in subsystem QUSRWR 
Job 165802/QUSER/QSCWCHPS ended on 25/06/25 at 09:01:00; 0,028 seconds used;  
Job 165801/QUSER/QSCWCHPS ended on 25/06/25 at 09:01:00; 0,027 seconds used;  
*SIGNON server job 165376/QUSER/QZSOSIGN processing request for user SAYTEL o 
User SAYTEL from client 127.0.0.1 connected to job 165436/QUSER/QZDASOINIT in 
Job 165808/QUSER/QSCWCHPS started on 25/06/25 at 09:01:59 in subsystem QUSRWR_

**Comment by NicolaeCh** [comment]
I saw this in manzan_debug.txt but the message doesn't appear in Loki: 
ÄINFOÜ Sending message ä                                                        
    "EVENT_TYPE":"message",                                                     
    "SESSION_ID":"ANSIBLE1",                                                    
    "JOB":"165955/QUSER/QZSOSIGN",                                              
    "MESSAGE_ID":"CPIAD0B",                                                     
    "MESSAGE_TYPE":"*INFO",                                                     
    "SEVERITY": 0,                                                              
    "MESSAGE_TIMESTAMP":"2025-06-25 09:34:00.892",                              
    "SENDING_USRPRF":"QUSER",                                                   
    "MESSAGE":"El trabajo servidor *SIGNON 165955/QUSER/QZSOSIGN está procesando
    "SENDING_PROGRAM_NAME":"QZSOSIGN",                                          
    "SENDING_MODULE_NAME":"          ",            
    "SENDING_MODULE_NAME":"          ",                                        
    "SENDING_PROCEDURE_NAME":""                                                
üÄINFOÜ Conversion to UTF-8 successful.                                        
ÄINFOÜ Connected to server at 127.0.0.1:8080                                   
ÄINFOÜ Socket port:                                                            
ÄINFOÜ Sent message: Cu      áîá+è¬èß&á   _ÁËË/ÅÁ        ëáëë¦|+¬¦à    +ë¦â<á  
ÄINFOÜ Connected to server at 127.0.0.1:8080                                   
ÄINFOÜ Socket closed                                                           
ÄINFOÜ Published                                                               
ÄINFOÜ DONE                                                                    
ÄINFOÜ Sent message: Cu      áîá+è¬èß&á   _ÁËË/ÅÁ        ëáëë¦|+¬¦à    +ë¦â<á  
ÄINFOÜ Socket closed                                                           
ÄINFOÜ Published                                                               
ÄINFOÜ DONE

**Comment by jonnyz32** [comment]
Hi @NicolaeCh, based on the manzan_debug.txt output it looks like the message was sent. Do you have the output from the manzan jar file that was running? I wonder if there was an error message. Can you try running it again but add this to your dests.ini

```
[stdout]
type=stdout
``` 

and change your data.ini to have this for the histlog
```
[watchout]
type=watch
id=ansible1
destinations=stdout
strwch=WCHMSG((*ALL)) WCHMSGQ((*HSTLOG))
interval=60000
numToProcess=100
enabled=true
```

Seeing the standard out after running it this way will be insightful.

**Comment by NicolaeCh** [comment]
Done. @jonnyz32 have a look at log file - it seems that there are some char conversions error. My system is Spanish - CCSID 284

**Comment by jonnyz32** [comment]
@NicolaeCh Thanks! I will investigate.

**Comment by NicolaeCh** [comment]
[manzan_debug (2).txt](https://github.com/user-attachments/files/20908820/manzan_debug.2.txt)

**Comment by NicolaeCh** [comment]
And here you have the corresponding data from manzan_debug - just in case it helps you.

**Comment by jonnyz32** [comment]
I changed my user profile ccsid to 284 to try to reproduce, but I'm still not getting the same error as @NicolaeCh . Here's the output I got after changing my ccsid, and recompiling the handler program.

```
¢INFO! Sending message {
    "EVENT_TYPE":"message",
    "SESSION_ID":"SKXHZX",
    "JOB":"080178/QUSER/QZRCSRVS",
    "MESSAGE_ID":"CPIAD09",
    "MESSAGE_TYPE":"*INFO",
    "SEVERITY": 0,
    "MESSAGE_TIMESTAMP":"2025-06-25 21:01:47.488",
    "SENDING_USRPRF":"JONATHAN",
    "MESSAGE":"User JONATHAN from client 127.0.0.1 connected to job 080178/QUSER/QZRCSRVS in subsystem QUSRWRK in QSYS on 06/25/25 21:01:47.",
    "SENDING_PROGRAM_NAME":"QZBSSECR",
    "SENDING_MODULE_NAME":"          ",
    "SENDING_PROCEDURE_NAME":""
}¢INFO! Conversion to UTF-8 successful.
```
Any ideas @SanjulaGanepola @worksofliam @ThePrez  . In their log, the { of the json message was replaced with ä

**Comment by jonnyz32** [comment]
@NicolaeCh I'm guessing all the systems are using ccsid 284? And what about the user profile?

**Comment by NicolaeCh** [comment]
Hi @jonnyz32 - it worked. Compiling with TGTCCSID(37) solved the problem I have no all the messages in Loki. Even debug messages looks better: 
    "SENDING_PROGRAM_NAME":"QZBSSECR",                                         
    "SENDING_MODULE_NAME":"          ",                                        
    "SENDING_PROCEDURE_NAME":""                                                
}^INFO! Connected to server at 127.0.0.1:8080                                  
^INFO! Conversion to UTF-8 successful.                                         
^INFO! Socket port:                                                            
^INFO! Sent message: Ñ      áîá+è¬èß&á   _ÁËË/ÅÁ        ëáëë¦|+¬¦à    +ë¬ç¦ëè  
^INFO! Socket closed              
^INFO! Socket closed                                                           
^INFO! Connected to server at 127.0.0.1:8080                                   
^INFO! Published                                                               
^INFO! DONE                                                                    
^INFO! Sent message: Ñ      áîá+è¬èß&á   _ÁËË/ÅÁ        ëáëë¦|+¬¦à    +ë¬ç¦ëè  
^INFO! Socket closed                                                           
^INFO! Published                                                               
^INFO! DONE                                                                    
^INFO! Watch program called. Watch option setting is '*MSGID'                  
^INFO! Handling message                                                        
^INFO! Timestamp is '2025-06-27 10:04:07.868'                                  
^INFO! Replacement data offset is '492'                                        
^INFO! REPLACEMENT DATA LENGTH IS '68'                                         
^INFO! MESSAGE WATCHED IS 'CPIAD0B'                                            
^INFO! MESSAGE FILE AND NAME IS 'QCPFMSG   QSYS      '
